#!/bin/busybox sh
/bin/busybox --install -s
export PATH=/usr/bin:/usr/sbin:/bin:/sbin
echo "Tinyn1x Init 1.0"
uname -a
mount -t proc none /proc
mount -t sysfs none /sys
mkdir /dev/shm /dev/pts
chmod 777 /dev/shm
mount -t devpts none /dev/pts
mount -t tmpfs -o size=1M none /dev/shm
checkra1n -cv
halt
